@startuml
    File <--> Uploader
    File --> Config
    class File{
        -fileSize:int
        -creationDate:int
        -type:String
        -userID:int
        -userName:String
        -tags:String[]
        -filename:String
        -description:String
        -folderpath:String
        --
        +__construct(dir:String, filename:String)<<constructor>>
        +fileExists():bool
        -evaluateType():void
        +deleteFile():bool
        +addFile():bool
        +updateFileInfo():bool
        +renameFile(name:String):bool
        +setTags(tags:String[]):void
        +setDescription(description:String):void
        +setUser(userID:int):void
        +getDescription():String
        +getTags():String[]
        +getFileContent():String
        +getFileName():String
        +getFolderPath():String
        +getFullPath():String
        +getFileSize():int
        +getCreationDate():int
        +getType():String
        
    }

    class Uploader{
        -errorCode:int
        -targetDir:String
        --
        +__construct(FileSuperGlobal:String[])<<constructor>>
        +setTargetDir(targetDir:String):bool
        +moveFiletoTarget():bool
        -targetFolderExist():bool

    }

    class Config{
        +folder:String
    }

    note left
        Contains the 
        path were the 
        panel is located
    end note
@enduml