 @startuml
 entity files{
        *id:int [Auto Increment][Primary Key]
        *tags:TEXT
        *description:TEXT
        *fileName:TEXT
        *folderPath:TEXT
    } 

    entity users{
        *user_id:int [Auto Increment][Primary Key]
        *username:VARCHAR(256)
        *password:VARCHAR(256)
        *email:VARCHAR(256)
        *lastLogin:TIMESTAMP
        *sessionID:VARCHAR(32)
        *role_id:int
    }

    entity user_has_file{
        *file_id:int[Foreign Key]
        *user_id:int[Foreign Key]
    }

    user_has_file ..|| files
    user_has_file ..|| users
@enduml